 version: 0.2

env:
  variables:
    PROJECT: AspNetMvcSampleApp
    DOTNET_FRAMEWORK: 4.7.2
phases:
  build:
    commands:
      - cd demoproject && nuget restore
      - msbuild demoproject.csproj /p:Configuration=Release /p:OutDir=C:\codebuild\artifacts\ /t:build
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\'
