version: 0.2

env:
  variables:
    PROJECT: AspNetMvcSampleApp
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore
      - msbuild $env:PROJECT.csproj /p:Configuration=Release /p:OutDir=C:\codebuild\artifacts\ /t:build
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\'
